### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by abccbaandy** [daanvdh/JavaForger#4]
I got this error when I run
````
Exception in thread "main" java.lang.NullPointerException
	at reader.ClassContainerReader.resolve(ClassContainerReader.java:190)
	at reader.ClassContainerReader.resolveAndSetImport(ClassContainerReader.java:182)
	at reader.ClassContainerReader.parseField(ClassContainerReader.java:162)
	at reader.ClassContainerReader.readCompilationUnit(ClassContainerReader.java:95)
	at reader.ClassContainerReader.read(ClassContainerReader.java:67)
	at generator.TemplateInputParametersService.getInputParameters(TemplateInputParametersService.java:59)
	at generator.Generator.execute(Generator.java:72)
	at generator.Generator.execute(Generator.java:66)
	at generator.JavaForger.execute(JavaForger.java:64)
`````

**Comment by daanvdh** [comment]
Oops, you're right. This has been fixed already in a different branch, will deploy that to the maven repository as soon as possible. You will unfortunately have to build two projects as a quick fix, because the new project JavaForger depends on is also not deployed to the maven repository. 

Quick fix: 
- clone JavaForger
- checkout feature/dataflow2 
- clone JavaDataFlow (https://github.com/daanvdh/JavaDataFlow )
- checkout master 
- build both projects and use 2.0.0-SNAPSHOT as version for JavaForger in your pom. 

I will let you know in this issue if the real fix is deployed.

**Comment by daanvdh** [comment]
Ok should be fixed now. Use the following in your pom: 

    <dependency>
      <groupId>com.github.daanvdh.javaforger</groupId>
      <artifactId>JavaForger</artifactId>
      <version>2.0.0</version>
    </dependency>

Let me know if you find anything else. You can close the issue if it's fixed.
